apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample2
  namespace: application-service-system
spec:
  replicas: 2
  selector: null
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: FOO2
          value: BAR23
        image: quay.io/redhat-appstudio/user-workload:application-service-system-component-sample2
        name: container-image
        resources:
          limits:
            cpu: "2"
            memory: 500Mi
            storage: 400Mi
          requests:
            cpu: 700m
            memory: 400Mi
            storage: 200Mi
status: {}
